// GENERATED by scripts/sync-templates.mjs — do not edit.
// Source of truth: src/battinfo/data/examples/cell-spec/research/ (8 templates).
// Identity and provenance are stripped; the form asks for them per record.
// Regenerate with `npm run sync:templates`; CI fails if this file drifts.

export const TEMPLATES: { slug: string; format: string; record: Record<string, unknown> }[] = [
  {
    "slug": "a123-anr26650m1-b.detailed",
    "format": "cylindrical",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/zj8t-t6sa-qx3j-e1xj",
        "name": "A123 ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123"
        },
        "model": "ANR26650M1-B",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite",
        "size_code": "R26650"
      },
      "properties": {
        "nominal_capacity": {
          "typical_value": 2.5,
          "unit": "Ah"
        },
        "rated_capacity": {
          "value": 2.4,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V"
        },
        "charging_voltage": {
          "value": 3.65,
          "unit": "V"
        },
        "discharging_cutoff_voltage": {
          "value": 2,
          "unit": "V"
        },
        "nominal_continuous_charging_current": {
          "value": 2.5,
          "unit": "A"
        },
        "maximum_continuous_charging_current": {
          "value": 2.5,
          "unit": "A"
        },
        "pulse_charging_current": {
          "max_value": 10,
          "unit": "A"
        },
        "nominal_continuous_discharging_current": {
          "value": 50,
          "unit": "A"
        },
        "maximum_continuous_discharging_current": {
          "value": 50,
          "unit": "A"
        },
        "pulse_discharging_current": {
          "max_value": 120,
          "unit": "A"
        },
        "minimum_charging_temperature": {
          "value": 0,
          "unit": "degC"
        },
        "maximum_charging_temperature": {
          "value": 45,
          "unit": "degC"
        },
        "minimum_discharging_temperature": {
          "value": -20,
          "unit": "degC"
        },
        "maximum_discharging_temperature": {
          "value": 60,
          "unit": "degC"
        },
        "minimum_storage_temperature": {
          "value": -20,
          "unit": "degC"
        },
        "maximum_storage_temperature": {
          "value": 45,
          "unit": "degC"
        },
        "cycle_life": {
          "value": 2000,
          "unit": "count"
        },
        "diameter": {
          "value": 26,
          "unit": "mm"
        },
        "height": {
          "value": 65.2,
          "unit": "mm"
        },
        "mass": {
          "value": 76,
          "unit": "g"
        },
        "volume": {
          "value": 0.0346,
          "unit": "L"
        },
        "specific_energy": {
          "value": 108.6,
          "unit": "Wh/kg"
        },
        "energy_density": {
          "value": 238,
          "unit": "Wh/L"
        },
        "internal_resistance": {
          "value": 6,
          "unit": "milliohm"
        },
        "impedance": {
          "value_text": "5-8 (1 kHz, 50% SOC)",
          "unit": "milliohm"
        }
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.935,
                    "unit": "1"
                  },
                  "particle_d50": {
                    "value": 1.8,
                    "unit": "um"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              },
              {
                "name": "Al2O3 coating particles",
                "property": {
                  "mass_fraction": {
                    "value": 0.005,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 20,
              "unit": "mg/cm^2"
            },
            "porosity": {
              "value": 0.35,
              "unit": "1"
            },
            "thickness": {
              "value": 66,
              "unit": "um"
            }
          },
          "comment": "Representative production coating composition."
        },
        "current_collector": {
          "name": "Al foil",
          "property": {
            "thickness": {
              "value": 15,
              "unit": "um"
            },
            "areal_mass": {
              "value": 40.5,
              "unit": "mg/cm^2"
            }
          },
          "comment": "Etched aluminum collector."
        },
        "property": {
          "compaction_density": {
            "value": 2.34,
            "unit": "g/cm^3"
          }
        },
        "comment": "Positive electrode parameters from internal recipe."
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.04,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.01,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 11.2,
              "unit": "mg/cm^2"
            },
            "thickness": {
              "value": 78,
              "unit": "um"
            }
          },
          "comment": "Representative negative coating."
        },
        "current_collector": {
          "name": "Cu foil",
          "property": {
            "thickness": {
              "value": 10,
              "unit": "um"
            }
          }
        },
        "comment": "Negative electrode with graphite-dominant active material."
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.3,
                  "unit": "1"
                }
              }
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.7,
                  "unit": "1"
                }
              }
            }
          ],
          "property": {
            "water_content": {
              "max_value": 20,
              "unit": "ppm"
            }
          },
          "comment": "Base solvent system."
        },
        "salt": {
          "name": "LiPF6",
          "cation": "Li+",
          "anion": "PF6-",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          },
          "comment": "Standard 1M salt concentration."
        },
        "additive": [
          {
            "name": "VC",
            "property": {
              "volume_fraction": {
                "value": 0.02,
                "unit": "1"
              }
            }
          },
          {
            "name": "FEC",
            "property": {
              "volume_fraction": {
                "value": 0.03,
                "unit": "1"
              }
            }
          }
        ],
        "property": {
          "conductivity": {
            "value": 10.5,
            "unit": "mS/cm"
          },
          "viscosity": {
            "value": 2.4,
            "unit": "mPa*s"
          }
        },
        "comment": "Electrolyte composition at 25 C."
      },
      "separator": {
        "material": "PE/PP trilayer",
        "property": {
          "thickness": {
            "value": 20,
            "unit": "um"
          },
          "porosity": {
            "value": 0.42,
            "unit": "1"
          }
        },
        "comment": "Microporous polyolefin separator."
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "Catenaro 2021 ingestion pilot",
        "source_file": "sources/a123/anr26650m1-b/catenaro-2021/battery.json",
        "source_url": "https://doi.org/10.17632/kxsbr4x3j2.2",
        "retrieved_at": 1772556000,
        "workflow_version": "battinfo-ingest-0.2.0",
        "comment": "Manually curated example for schema validation and RDF mapping review.",
        "citation": "https://doi.org/10.17632/kxsbr4x3j2.2"
      },
      "notes": [
        "Primary review artifact for BattINFO/BDF battery descriptor structure.",
        "Values are representative and intended for schema/mapping review.",
        "This is the primary end-to-end review file for battery descriptor changes.",
        "Update this file whenever schema or mapping decisions change."
      ]
    }
  },
  {
    "slug": "coin-detailed",
    "format": "coin",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/1c4m-7p9q-2k6t-8v3r",
        "name": "ExampleLab COIN-LFP-2032",
        "manufacturer": {
          "type": "Organization",
          "name": "ExampleLab"
        },
        "model": "COIN-LFP-2032",
        "cell_format": "coin",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite",
        "size_code": "2032"
      },
      "properties": {
        "nominal_capacity": {
          "value": 0.04,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.2,
          "unit": "V"
        }
      },
      "construction": {
        "assembly_type": "stacked",
        "layering": "not_applicable",
        "comment": "Coin-cell example fixture with stacked pellet-style components."
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.92,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.04,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.04,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "thickness": {
              "value": 55,
              "unit": "um"
            }
          }
        },
        "current_collector": {
          "name": "Al foil"
        }
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.05,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "thickness": {
              "value": 48,
              "unit": "um"
            }
          }
        },
        "current_collector": {
          "name": "Cu foil"
        }
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.5,
                  "unit": "1"
                }
              }
            },
            {
              "name": "DEC",
              "property": {
                "volume_fraction": {
                  "value": 0.5,
                  "unit": "1"
                }
              }
            }
          ]
        },
        "salt": {
          "name": "LiPF6",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          }
        }
      },
      "separator": {
        "material": "PP membrane",
        "property": {
          "thickness": {
            "value": 20,
            "unit": "um"
          }
        }
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO example fixtures",
        "source_file": "examples/cell-descriptors/coin-detailed.example.json",
        "retrieved_at": 1773201600,
        "workflow_version": "example-fixtures-0.1",
        "comment": "Canonical detailed coin-cell fixture."
      },
      "notes": [
        "Detailed coin-cell descriptor for validation coverage.",
        "Example fixture for detailed coin-cell descriptions."
      ]
    }
  },
  {
    "slug": "cylindrical-detailed",
    "format": "cylindrical",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/2d5n-8r4k-3p7t-6v9m",
        "name": "ExampleLab CYL-LFP-18650",
        "manufacturer": {
          "type": "Organization",
          "name": "ExampleLab"
        },
        "model": "CYL-LFP-18650",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite",
        "size_code": "18650"
      },
      "properties": {
        "nominal_capacity": {
          "value": 1.5,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.2,
          "unit": "V"
        }
      },
      "construction": {
        "assembly_type": "wound",
        "layering": "multilayer",
        "layer_count": 32,
        "comment": "Jelly-roll cylindrical example fixture."
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.94,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 17.5,
              "unit": "mg/cm^2"
            },
            "thickness": {
              "value": 64,
              "unit": "um"
            }
          }
        },
        "current_collector": {
          "name": "Al foil",
          "property": {
            "thickness": {
              "value": 15,
              "unit": "um"
            }
          }
        }
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.05,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "thickness": {
              "value": 72,
              "unit": "um"
            }
          }
        },
        "current_collector": {
          "name": "Cu foil",
          "property": {
            "thickness": {
              "value": 10,
              "unit": "um"
            }
          }
        }
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.3,
                  "unit": "1"
                }
              }
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.7,
                  "unit": "1"
                }
              }
            }
          ]
        },
        "salt": {
          "name": "LiPF6",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          }
        },
        "additive": [
          {
            "name": "VC",
            "property": {
              "volume_fraction": {
                "value": 0.02,
                "unit": "1"
              }
            }
          }
        ]
      },
      "separator": {
        "material": "PE/PP trilayer",
        "property": {
          "thickness": {
            "value": 18,
            "unit": "um"
          }
        }
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO example fixtures",
        "source_file": "examples/cell-descriptors/cylindrical-detailed.example.json",
        "retrieved_at": 1773201600,
        "workflow_version": "example-fixtures-0.1",
        "comment": "Canonical detailed cylindrical fixture."
      },
      "notes": [
        "Detailed cylindrical descriptor for validation coverage.",
        "Example fixture for detailed cylindrical-cell descriptions."
      ]
    }
  },
  {
    "slug": "extended",
    "format": "cylindrical",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/pmgd-9cyx-z05w-yajf",
        "name": "A123 ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123"
        },
        "model": "ANR26650M1-B",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite",
        "size_code": "R26650"
      },
      "properties": {
        "nominal_capacity": {
          "typical_value": 2.5,
          "unit": "Ah"
        },
        "rated_capacity": {
          "value": 2.4,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.3,
          "unit": "V"
        },
        "continuous_discharging_current": {
          "max_value": 50,
          "unit": "A"
        },
        "cycle_life": {
          "value": 2000,
          "unit_text": "count"
        },
        "impedance": {
          "value_text": "5-8 (1 kHz, 50% SOC)",
          "unit": "milliohm"
        }
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.935,
                    "unit": "1"
                  },
                  "particle_d50": {
                    "value": 1.8,
                    "unit": "um"
                  }
                },
                "comment": "Main active component."
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                },
                "comment": "Polymer binder."
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                },
                "comment": "Conductivity additive."
              },
              {
                "name": "Al2O3 particles",
                "property": {
                  "mass_fraction": {
                    "value": 0.005,
                    "unit": "1"
                  }
                },
                "comment": "Coating stabilizer."
              }
            ]
          },
          "property": {
            "loading": {
              "value": 20,
              "unit": "mg/cm^2"
            },
            "thickness": {
              "value": 66,
              "unit": "um"
            },
            "porosity": {
              "value": 0.35,
              "unit": "1"
            }
          },
          "comment": "Representative positive electrode coating."
        },
        "current_collector": {
          "name": "Al foil",
          "property": {
            "thickness": {
              "value": 15,
              "unit": "um"
            },
            "areal_mass": {
              "value": 40.5,
              "unit": "mg/cm^2"
            }
          },
          "comment": "Etched aluminum collector."
        },
        "property": {
          "compaction_density": {
            "value": 2.34,
            "unit": "g/cm^3"
          }
        },
        "comment": "Positive electrode metadata block."
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                },
                "comment": "Main negative active material."
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.04,
                    "unit": "1"
                  }
                },
                "comment": "Binder blend."
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.01,
                    "unit": "1"
                  }
                },
                "comment": "Electronic conduction additive."
              },
              {
                "name": "SiOx",
                "property": {
                  "mass_fraction": {
                    "value": 0,
                    "unit": "1"
                  }
                },
                "comment": "Placeholder example to exercise schema option."
              }
            ]
          },
          "property": {
            "loading": {
              "value": 11.2,
              "unit": "mg/cm^2"
            },
            "thickness": {
              "value": 78,
              "unit": "um"
            }
          },
          "comment": "Representative negative electrode coating."
        },
        "current_collector": {
          "name": "Cu foil",
          "property": {
            "thickness": {
              "value": 10,
              "unit": "um"
            }
          },
          "comment": "Copper current collector."
        },
        "property": {
          "compaction_density": {
            "value": 1.7,
            "unit": "g/cm^3"
          }
        },
        "comment": "Negative electrode metadata block."
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.3,
                  "unit": "1"
                }
              },
              "comment": "High dielectric solvent."
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.7,
                  "unit": "1"
                }
              },
              "comment": "Low-viscosity co-solvent."
            }
          ],
          "property": {
            "water_content": {
              "max_value": 20,
              "unit": "ppm"
            }
          },
          "comment": "Base solvent system."
        },
        "salt": {
          "name": "LiPF6",
          "cation": "Li+",
          "anion": "PF6-",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          },
          "comment": "Primary conducting salt."
        },
        "additive": [
          {
            "name": "VC",
            "property": {
              "volume_fraction": {
                "value": 0.02,
                "unit": "1"
              }
            },
            "comment": "SEI-forming additive."
          },
          {
            "name": "FEC",
            "property": {
              "volume_fraction": {
                "value": 0.03,
                "unit": "1"
              }
            },
            "comment": "Film-forming additive."
          }
        ],
        "property": {
          "conductivity": {
            "value": 10.5,
            "unit": "mS/cm"
          },
          "viscosity": {
            "value": 2.4,
            "unit": "mPa*s"
          }
        },
        "comment": "Electrolyte metadata block."
      },
      "separator": {
        "material": "PE/PP trilayer",
        "property": {
          "thickness": {
            "value": 20,
            "unit": "um"
          },
          "porosity": {
            "value": 0.42,
            "unit": "1"
          }
        },
        "comment": "Microporous separator."
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO schema examples",
        "source_file": "examples/cell-descriptors/extended.example.json",
        "source_url": "https://w3id.org/battinfo",
        "retrieved_at": 1773000000,
        "workflow_version": "battinfo-refactor",
        "comment": "Created as a complementary full-option example.",
        "citation": "https://w3id.org/battinfo"
      },
      "notes": [
        "Extended example includes all optional descriptor sections.",
        "Values are illustrative and for schema integration/testing.",
        "This file complements minimal.example.json.",
        "Use this as a template for rich battery-cell descriptions."
      ]
    }
  },
  {
    "slug": "minimal",
    "format": "cylindrical",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/pvn1-43h7-rm3e-mjqq",
        "name": "A123 ANR26650M1-B",
        "manufacturer": {
          "type": "Organization",
          "name": "A123"
        },
        "model": "ANR26650M1-B",
        "cell_format": "cylindrical",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite"
      },
      "provenance": {
        "source_type": "manual"
      }
    }
  },
  {
    "slug": "pouch-multilayer-detailed",
    "format": "pouch",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/4h8p-3t6m-9q2k-7v5r",
        "name": "ExampleLab POUCH-ML-LFP-018",
        "manufacturer": {
          "type": "Organization",
          "name": "ExampleLab"
        },
        "model": "POUCH-ML-LFP-018",
        "cell_format": "pouch",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite"
      },
      "properties": {
        "nominal_capacity": {
          "value": 5,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.2,
          "unit": "V"
        }
      },
      "construction": {
        "assembly_type": "stacked",
        "layering": "multilayer",
        "layer_count": 18,
        "comment": "Multilayer pouch example fixture."
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.94,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 21,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Al foil"
        }
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.05,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 12,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Cu foil"
        }
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.3,
                  "unit": "1"
                }
              }
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.7,
                  "unit": "1"
                }
              }
            }
          ]
        },
        "salt": {
          "name": "LiPF6",
          "property": {
            "concentration": {
              "value": 1.1,
              "unit": "mol/L"
            }
          }
        },
        "additive": [
          {
            "name": "VC",
            "property": {
              "volume_fraction": {
                "value": 0.02,
                "unit": "1"
              }
            }
          }
        ]
      },
      "separator": {
        "material": "Ceramic-coated PE",
        "property": {
          "thickness": {
            "value": 20,
            "unit": "um"
          }
        }
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO example fixtures",
        "source_file": "examples/cell-descriptors/pouch-multilayer-detailed.example.json",
        "retrieved_at": 1773201600,
        "workflow_version": "example-fixtures-0.1",
        "comment": "Canonical detailed multilayer pouch fixture."
      },
      "notes": [
        "Detailed multilayer pouch descriptor for validation coverage.",
        "Example fixture for detailed multilayer pouch-cell descriptions."
      ]
    }
  },
  {
    "slug": "pouch-single-layer-detailed",
    "format": "pouch",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/3f7k-2m9r-4t6p-8v5q",
        "name": "ExampleLab POUCH-SL-LFP-001",
        "manufacturer": {
          "type": "Organization",
          "name": "ExampleLab"
        },
        "model": "POUCH-SL-LFP-001",
        "cell_format": "pouch",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite"
      },
      "properties": {
        "nominal_capacity": {
          "value": 0.12,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.2,
          "unit": "V"
        }
      },
      "construction": {
        "assembly_type": "stacked",
        "layering": "single_layer",
        "layer_count": 1,
        "comment": "Single-layer pouch example fixture."
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.93,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.04,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 14,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Al foil"
        }
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.05,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 8,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Cu foil"
        }
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.4,
                  "unit": "1"
                }
              }
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.6,
                  "unit": "1"
                }
              }
            }
          ]
        },
        "salt": {
          "name": "LiPF6",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          }
        }
      },
      "separator": {
        "material": "PP membrane",
        "property": {
          "thickness": {
            "value": 16,
            "unit": "um"
          }
        }
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO example fixtures",
        "source_file": "examples/cell-descriptors/pouch-single-layer-detailed.example.json",
        "retrieved_at": 1773201600,
        "workflow_version": "example-fixtures-0.1",
        "comment": "Canonical detailed single-layer pouch fixture."
      },
      "notes": [
        "Detailed single-layer pouch descriptor for validation coverage.",
        "Example fixture for detailed single-layer pouch-cell descriptions."
      ]
    }
  },
  {
    "slug": "prismatic-detailed",
    "format": "prismatic",
    "record": {
      "schema_version": "0.2.0",
      "cell_spec": {
        "id": "https://w3id.org/battinfo/spec/5j9r-4k7p-2m8t-6v3q",
        "name": "ExampleLab PRISM-LFP-020",
        "manufacturer": {
          "type": "Organization",
          "name": "ExampleLab"
        },
        "model": "PRISM-LFP-020",
        "cell_format": "prismatic",
        "chemistry": "Li-ion",
        "positive_electrode_basis": "LFP",
        "negative_electrode_basis": "graphite"
      },
      "properties": {
        "nominal_capacity": {
          "value": 20,
          "unit": "Ah"
        },
        "nominal_voltage": {
          "value": 3.2,
          "unit": "V"
        }
      },
      "construction": {
        "assembly_type": "stacked",
        "layering": "multilayer",
        "layer_count": 24,
        "comment": "Stacked prismatic example fixture."
      },
      "positive_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "LFP",
                "property": {
                  "mass_fraction": {
                    "value": 0.94,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "PVDF",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ],
            "additive": [
              {
                "name": "Carbon black",
                "property": {
                  "mass_fraction": {
                    "value": 0.03,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 24,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Al foil"
        }
      },
      "negative_electrode": {
        "coating": {
          "component": {
            "active_material": [
              {
                "name": "Graphite",
                "property": {
                  "mass_fraction": {
                    "value": 0.95,
                    "unit": "1"
                  }
                }
              }
            ],
            "binder": [
              {
                "name": "CMC/SBR",
                "property": {
                  "mass_fraction": {
                    "value": 0.05,
                    "unit": "1"
                  }
                }
              }
            ]
          },
          "property": {
            "loading": {
              "value": 13,
              "unit": "mg/cm^2"
            }
          }
        },
        "current_collector": {
          "name": "Cu foil"
        }
      },
      "electrolyte": {
        "family": "organic",
        "solvent_mixture": {
          "component": [
            {
              "name": "EC",
              "property": {
                "volume_fraction": {
                  "value": 0.25,
                  "unit": "1"
                }
              }
            },
            {
              "name": "EMC",
              "property": {
                "volume_fraction": {
                  "value": 0.75,
                  "unit": "1"
                }
              }
            }
          ]
        },
        "salt": {
          "name": "LiPF6",
          "property": {
            "concentration": {
              "value": 1,
              "unit": "mol/L"
            }
          }
        },
        "additive": [
          {
            "name": "FEC",
            "property": {
              "volume_fraction": {
                "value": 0.03,
                "unit": "1"
              }
            }
          }
        ]
      },
      "separator": {
        "material": "Ceramic-coated PP",
        "property": {
          "thickness": {
            "value": 18,
            "unit": "um"
          }
        }
      },
      "provenance": {
        "source_type": "manual",
        "source_name": "BattINFO example fixtures",
        "source_file": "examples/cell-descriptors/prismatic-detailed.example.json",
        "retrieved_at": 1773201600,
        "workflow_version": "example-fixtures-0.1",
        "comment": "Canonical detailed prismatic fixture."
      },
      "notes": [
        "Detailed prismatic descriptor for validation coverage.",
        "Example fixture for detailed prismatic-cell descriptions."
      ]
    }
  }
];
