// Build-time vocabulary sync — vendored-with-sync, like sync-schemas.mjs.
//
// A unit or an electrode-basis is a plain string in JSON Schema, so the schemas
// cannot say which values are recognised. The curated terms live in
// assets/mappings/domain-battery/**, which the JSON→JSON-LD transform also
// reads. The authoring form offers the same terms as suggestions, so a record
// is written in the vocabulary the transform can map.
//
// Those files sit outside web/, which the bundler will not resolve, so they are
// embedded into a GENERATED, COMMITTED module the same way the schemas are.
//
//   Run:   npm run sync:vocab
//   CI:    npm run sync:vocab -- --check   (fails on drift)
//
// No dependencies; Node ESM only.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..");
const MAPPINGS = resolve(repoRoot, "assets", "mappings", "domain-battery");
const OUT = resolve(here, "..", "lib", "vocab.generated.ts");

function symbols(file) {
  const parsed = JSON.parse(readFileSync(resolve(MAPPINGS, file), "utf-8"));
  const seen = new Set();
  for (const entry of parsed.mappings ?? []) {
    if (typeof entry?.symbol === "string" && entry.symbol) seen.add(entry.symbol);
  }
  return [...seen];
}

const units = symbols("unit_map.curated.json");
const materials = symbols("material_map.json");

const body =
  `// GENERATED by scripts/sync-vocab.mjs — do not edit.\n` +
  `// Source of truth: assets/mappings/domain-battery/ (${units.length} units, ${materials.length} materials).\n` +
  `// Regenerate with \`npm run sync:vocab\`; CI fails if this file drifts.\n\n` +
  `export const UNIT_SYMBOLS: string[] = ${JSON.stringify(units, null, 2)};\n\n` +
  `export const MATERIAL_SYMBOLS: string[] = ${JSON.stringify(materials, null, 2)};\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf-8") : "";
  if (current.replace(/\r\n/g, "\n") !== body.replace(/\r\n/g, "\n")) {
    console.error(
      "lib/vocab.generated.ts drifts from assets/mappings/domain-battery/**.\n" +
        "Run `npm run sync:vocab` in web/ and commit the result.",
    );
    process.exit(1);
  }
  console.log(`vocabularies in sync (${units.length} units, ${materials.length} materials).`);
} else {
  writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (${units.length} units, ${materials.length} materials).`);
}
